/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.main;

import DemoTestFunction.mainForm;
import ExSwing.*;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author Administrator PC
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private String[] imageFile={"home.png","member_management.png","book_management.png"
            , "staff_management.png","ir_management.png","fine_management.png"};
    public Main() {
        initComponents();
        setResizable(false);
       
        
        setTitle(".:: Library Management System::.");
        setIconImage(Toolkit.getDefaultToolkit().getImage(
				Main.class.getResource("/image/main.png")));
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
     
        setContentPane(contentpane);
        contentpane.setBackground(Color.BLACK);
        addIconTabbedPane();
        //set panel Home        
        pnlHome.setLayout(null);
        jTabbedPane1.setBounds(5, 5, 809, 620);
        
        lblWelcome.setFont(new Font("Droid Sans", Font.BOLD, 36));
        lblWelcome.setForeground(new Color(255, 255, 255));
        lblWelcome.setBounds(200, 261, 573, 63);
        
        
        //background pnl home 2
//        JLabel lblBG = new JLabel("");
//        lblBG.setIcon(new ImageIcon(Main.class
//                        .getResource("/image/bgTab.png")));
//        lblBG.setBounds(5, 5, 799, 567);
//        pnlHome.add(lblBG);
                
        
        
      //set side panel 
        setSidePanelByMember(sidePanel);
     //background wall
        JLabel label_5 = new JLabel("");
        label_5.setIcon(new ImageIcon(Main.class
                        .getResource("/image/background.png")));
        label_5.setForeground(Color.WHITE);
        label_5.setBounds(0, 60, 1240, 620);
        contentpane.add(label_5);
        
       
       // validate();
    }
   
    private void addIconTabbedPane(){
        for(int i = 0; i < imageFile.length ; i++){
            jTabbedPane1.setIconAt(i, new ImageIcon( mainForm.class
						.getResource("/image/"+ imageFile[i])));
        }
        
    }
    private void setSidePanelByMember(JPanel content){
        content.removeAll();
        JLabel lblAdminAcc = new JLabel("Admin Account: ");
        lblAdminAcc.setForeground(Color.WHITE);
        lblAdminAcc.setFont(new Font("Droid Sans", Font.BOLD, 18));
        lblAdminAcc.setBounds(20, 25, 200, 17);
        content.add(lblAdminAcc);
        
        JLabel lblAdminNumber = new JLabel("2");
        lblAdminNumber.setForeground(Color.ORANGE);
        lblAdminNumber.setFont(new Font("Droid Sans", Font.BOLD, 18));
        lblAdminNumber.setBounds(200, 25, 200, 17);
        content.add(lblAdminNumber);
        
        
        /*
        JTextField txtWOToday = new ClRoundTransTxt();
        txtWOToday.setHorizontalAlignment(SwingConstants.RIGHT);
        txtWOToday.setForeground(Color.YELLOW);
        txtWOToday.setFont(new Font("Tahoma", Font.PLAIN, 35));
        txtWOToday.setEditable(false);
        txtWOToday.setColumns(4);
        // txtWOToday.setBackground(Color.BLACK);
        txtWOToday.setBounds(190, 20, 120, 45);
        content.add(txtWOToday);
        */
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentpane = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlHome = new ClGlossyPanel();
        lblWelcome = new LabelGradient("");
        bgHome = new javax.swing.JLabel();
        pnlMember = new ClGlossyPanel();
        iconMem1 = new javax.swing.JLabel();
        iconMem2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlBook = new ClGlossyPanel();
        iconMem3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        iconMem4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlStaff = new ClGlossyPanel();
        iconMem5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        iconMem6 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlIR = new ClGlossyPanel();
        iconMem7 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        iconMem8 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlFine = new ClGlossyPanel();
        iconMem9 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        iconMem10 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sidePanel = new ClPanelTransparent();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 5, 1166, 736));
        setPreferredSize(new java.awt.Dimension(1240, 700));

        contentpane.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1240, 720));

        lblWelcome.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.lblWelcome.text")); // NOI18N
        lblWelcome.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        bgHome.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.bgHome.text")); // NOI18N

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bgHome)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(lblWelcome)))
                .addGap(576, 576, 576))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addComponent(bgHome)
                .addGap(283, 283, 283)
                .addComponent(lblWelcome)
                .addContainerGap())
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(Main.class, "Main.pnlHome.TabConstraints.tabTitle"), pnlHome); // NOI18N

        iconMem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/member.png"))); // NOI18N
        iconMem1.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.iconMem1.text")); // NOI18N
        iconMem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMem1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconMem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMem1MouseClicked(evt);
            }
        });

        iconMem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/report.png"))); // NOI18N
        iconMem2.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.iconMem2.text")); // NOI18N
        iconMem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMem2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconMem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMem2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.jLabel1.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout pnlMemberLayout = new javax.swing.GroupLayout(pnlMember);
        pnlMember.setLayout(pnlMemberLayout);
        pnlMemberLayout.setHorizontalGroup(
            pnlMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemberLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(pnlMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconMem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110)
                .addGroup(pnlMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconMem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(421, Short.MAX_VALUE))
        );
        pnlMemberLayout.setVerticalGroup(
            pnlMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemberLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(pnlMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconMem2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconMem1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(Main.class, "Main.pnlMember.TabConstraints.tabTitle"), pnlMember); // NOI18N

        iconMem3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/report.png"))); // NOI18N
        iconMem3.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.iconMem3.text")); // NOI18N
        iconMem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMem3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconMem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMem3MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.jLabel3.text")); // NOI18N

        iconMem4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/book.png"))); // NOI18N
        iconMem4.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.iconMem4.text")); // NOI18N
        iconMem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMem4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconMem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMem4MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.jLabel4.text")); // NOI18N

        javax.swing.GroupLayout pnlBookLayout = new javax.swing.GroupLayout(pnlBook);
        pnlBook.setLayout(pnlBookLayout);
        pnlBookLayout.setHorizontalGroup(
            pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconMem4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110)
                .addGroup(pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconMem3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(373, 373, 373))
        );
        pnlBookLayout.setVerticalGroup(
            pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBookLayout.createSequentialGroup()
                        .addComponent(iconMem4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(pnlBookLayout.createSequentialGroup()
                        .addComponent(iconMem3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(Main.class, "Main.pnlBook.TabConstraints.tabTitle"), pnlBook); // NOI18N

        iconMem5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/staff.png"))); // NOI18N
        iconMem5.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.iconMem5.text")); // NOI18N
        iconMem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMem5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconMem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMem5MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.jLabel5.text")); // NOI18N

        iconMem6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/report.png"))); // NOI18N
        iconMem6.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.iconMem6.text")); // NOI18N
        iconMem6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMem6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconMem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMem6MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.jLabel6.text")); // NOI18N

        javax.swing.GroupLayout pnlStaffLayout = new javax.swing.GroupLayout(pnlStaff);
        pnlStaff.setLayout(pnlStaffLayout);
        pnlStaffLayout.setHorizontalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStaffLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconMem5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110)
                .addGroup(pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconMem6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(373, 373, 373))
        );
        pnlStaffLayout.setVerticalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStaffLayout.createSequentialGroup()
                        .addComponent(iconMem5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(pnlStaffLayout.createSequentialGroup()
                        .addComponent(iconMem6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(Main.class, "Main.pnlStaff.TabConstraints.tabTitle"), pnlStaff); // NOI18N

        pnlIR.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N

        iconMem7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ir.png"))); // NOI18N
        iconMem7.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.iconMem7.text")); // NOI18N
        iconMem7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMem7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconMem7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMem7MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.jLabel7.text")); // NOI18N

        iconMem8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/report.png"))); // NOI18N
        iconMem8.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.iconMem8.text")); // NOI18N
        iconMem8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMem8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconMem8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMem8MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.jLabel8.text")); // NOI18N

        javax.swing.GroupLayout pnlIRLayout = new javax.swing.GroupLayout(pnlIR);
        pnlIR.setLayout(pnlIRLayout);
        pnlIRLayout.setHorizontalGroup(
            pnlIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIRLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(pnlIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconMem7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110)
                .addGroup(pnlIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconMem8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(373, 373, 373))
        );
        pnlIRLayout.setVerticalGroup(
            pnlIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIRLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(pnlIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIRLayout.createSequentialGroup()
                        .addComponent(iconMem7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(pnlIRLayout.createSequentialGroup()
                        .addComponent(iconMem8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(Main.class, "Main.pnlIR.TabConstraints.tabTitle"), pnlIR); // NOI18N

        iconMem9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fine.png"))); // NOI18N
        iconMem9.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.iconMem9.text")); // NOI18N
        iconMem9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMem9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconMem9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMem9MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.jLabel9.text")); // NOI18N

        iconMem10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/report.png"))); // NOI18N
        iconMem10.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.iconMem10.text")); // NOI18N
        iconMem10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconMem10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconMem10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMem10MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.jLabel10.text")); // NOI18N

        javax.swing.GroupLayout pnlFineLayout = new javax.swing.GroupLayout(pnlFine);
        pnlFine.setLayout(pnlFineLayout);
        pnlFineLayout.setHorizontalGroup(
            pnlFineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFineLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(pnlFineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconMem9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110)
                .addGroup(pnlFineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconMem10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(373, 373, 373))
        );
        pnlFineLayout.setVerticalGroup(
            pnlFineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFineLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(pnlFineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFineLayout.createSequentialGroup()
                        .addComponent(iconMem9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(pnlFineLayout.createSequentialGroup()
                        .addComponent(iconMem10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(Main.class, "Main.pnlFine.TabConstraints.tabTitle"), pnlFine); // NOI18N

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.yellow);
        jLabel11.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.jLabel11.text")); // NOI18N

        jLabel12.setText(org.openide.util.NbBundle.getMessage(Main.class, "Main.jLabel12.text")); // NOI18N

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentpaneLayout = new javax.swing.GroupLayout(contentpane);
        contentpane.setLayout(contentpaneLayout);
        contentpaneLayout.setHorizontalGroup(
            contentpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentpaneLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(contentpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentpaneLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel11)
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(contentpaneLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        contentpaneLayout.setVerticalGroup(
            contentpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentpaneLayout.createSequentialGroup()
                .addGroup(contentpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentpaneLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iconMem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMem1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_iconMem1MouseClicked

    private void iconMem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMem2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iconMem2MouseClicked

    private void iconMem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMem3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iconMem3MouseClicked

    private void iconMem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMem4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iconMem4MouseClicked

    private void iconMem5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMem5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iconMem5MouseClicked

    private void iconMem6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMem6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iconMem6MouseClicked

    private void iconMem7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMem7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iconMem7MouseClicked

    private void iconMem8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMem8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iconMem8MouseClicked

    private void iconMem9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMem9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iconMem9MouseClicked

    private void iconMem10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMem10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iconMem10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main main = new Main();
                main.setVisible(true);
		main.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgHome;
    private javax.swing.JPanel contentpane;
    private javax.swing.JLabel iconMem1;
    private javax.swing.JLabel iconMem10;
    private javax.swing.JLabel iconMem2;
    private javax.swing.JLabel iconMem3;
    private javax.swing.JLabel iconMem4;
    private javax.swing.JLabel iconMem5;
    private javax.swing.JLabel iconMem6;
    private javax.swing.JLabel iconMem7;
    private javax.swing.JLabel iconMem8;
    private javax.swing.JLabel iconMem9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlBook;
    private javax.swing.JPanel pnlFine;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlIR;
    private javax.swing.JPanel pnlMember;
    private javax.swing.JPanel pnlStaff;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
